# Generated by Django 5.2.17 on 2026-08-29 14:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_cliente", models.CharField(max_length=150)),
                ("telefono", models.CharField(max_length=30)),
                ("direccion_entrega", models.TextField()),
                ("referencia_ubicacion", models.TextField(blank=True)),
                (
                    "monto_total_usd",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "tasa_cambio_usada",
                    models.DecimalField(decimal_places=6, max_digits=14),
                ),
                (
                    "monto_total_bs",
                    models.DecimalField(decimal_places=2, max_digits=16),
                ),
                (
                    "metodo_pago",
                    models.CharField(
                        choices=[
                            ("PAGO_MOVIL", "Pago móvil"),
                            ("EFECTIVO", "Efectivo"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("CONFIRMADO", "Confirmado"),
                            ("EN_CAMINO", "En camino"),
                            ("ENTREGADO", "Entregado"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-fecha_creacion",),
            },
        ),
        migrations.AlterModelOptions(
            name="tasacambio",
            options={
                "ordering": ("-fecha",),
                "verbose_name": "tasa de cambio",
                "verbose_name_plural": "tasas de cambio",
            },
        ),
        migrations.AddField(
            model_name="tasacambio",
            name="fecha",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tasacambio",
            name="valor_bs",
            field=models.DecimalField(decimal_places=6, max_digits=14),
        ),
        migrations.CreateModel(
            name="ComprobantePago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_referencia", models.CharField(max_length=100)),
                ("banco_origen", models.CharField(max_length=100)),
                (
                    "monto_pagado_bs",
                    models.DecimalField(decimal_places=2, max_digits=16),
                ),
                ("captura_url", models.URLField(blank=True, null=True)),
                (
                    "pedido",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comprobante",
                        to="orders.pedido",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DetallePedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField()),
                (
                    "precio_unitario_usd",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detalles_pedido",
                        to="orders.producto",
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="orders.pedido",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("pedido", "producto"),
                        name="detalle_producto_unico_por_pedido",
                    )
                ],
            },
        ),
    ]
