# Generated by Django 5.2.17 on 2026-09-06 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_pedido_alter_tasacambio_options_tasacambio_fecha_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="imagen",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
