# Generated by Django 5.2.17 on 2026-09-06 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_producto_imagen"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="detallepedido",
            name="detalle_producto_unico_por_pedido",
        ),
        migrations.AlterField(
            model_name="detallepedido",
            name="cantidad",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="detallepedido",
            name="pedido",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="orders.pedido"
            ),
        ),
        migrations.AlterField(
            model_name="detallepedido",
            name="precio_unitario_usd",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="detallepedido",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="orders.producto"
            ),
        ),
        migrations.AddConstraint(
            model_name="detallepedido",
            constraint=models.UniqueConstraint(
                fields=("pedido", "producto"), name="detalle_producto_unico"
            ),
        ),
    ]
