# Generated by Django 5.2.17 on 2026-09-12 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "orders",
            "0004_remove_detallepedido_detalle_producto_unico_por_pedido_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="detallepedido",
            name="detalle_producto_unico",
        ),
        migrations.AlterField(
            model_name="detallepedido",
            name="pedido",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalles",
                to="orders.pedido",
            ),
        ),
        migrations.AlterField(
            model_name="detallepedido",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="detalles_pedido",
                to="orders.producto",
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="metodo_pago",
            field=models.CharField(
                choices=[
                    ("PAGO_MOVIL", "Pago móvil"),
                    ("ZELLE", "Zelle"),
                    ("EFECTIVO", "Efectivo USD"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="detallepedido",
            constraint=models.UniqueConstraint(
                fields=("pedido", "producto"), name="detalle_producto_unico_por_pedido"
            ),
        ),
    ]
