# Generated by Django 5.2.17 on 2026-09-17 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_detallepedido_detalle_producto_unico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.CreateModel(
            name='Maridaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('chocolate', 'Chocolate'), ('habano', 'Habano'), ('carne', 'Carne / Comida')], max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maridajes', to='orders.producto')),
            ],
            options={
                'verbose_name': 'maridaje',
                'verbose_name_plural': 'maridajes',
            },
        ),
    ]
