# Generated by Django 5.2.17 on 2026-09-17 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_producto_descripcion_maridaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maridaje',
            name='tipo',
            field=models.CharField(choices=[('chocolate', 'Chocolate'), ('humo', 'Humo'), ('frituras', 'Frituras')], max_length=20),
        ),
    ]
