# Generated by Django 5.2.17 on 2026-09-17 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_maridaje_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maridaje',
            name='tipo',
            field=models.CharField(choices=[('chocolate', 'Chocolate / Dulces'), ('humo', 'Humo / Cigarrillos'), ('frituras', 'Frituras / Pasapalos'), ('charcuteria', 'Quesos y Embutidos'), ('frutos_secos', 'Frutos Secos'), ('carne', 'Carnes / Parrilla')], max_length=30),
        ),
    ]
