# Generated by Django 5.2.17 on 2026-09-17 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_maridaje_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maridaje',
            name='tipo',
            field=models.CharField(choices=[('chocolate', 'Chocolate / Dulces'), ('humo', 'Humo'), ('frituras', 'Frituras / Pasapalos'), ('frutos_secos', 'Frutos Secos')], max_length=30),
        ),
    ]
