# Generated by Django 5.2.17 on 2026-09-17 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_maridaje_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repartidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=30)),
                ('vehiculo', models.CharField(default='Moto Bera - Placa AB123C', max_length=100)),
                ('calificacion', models.DecimalField(decimal_places=1, default=5.0, max_digits=2)),
                ('foto_url', models.URLField(blank=True, max_length=500, null=True)),
                ('latitud_actual', models.FloatField(default=10.1333)),
                ('longitud_actual', models.FloatField(default=-64.7)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'repartidor',
                'verbose_name_plural': 'repartidores',
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='latitud_destino',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='longitud_destino',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tiempo_estimado',
            field=models.CharField(default='15-25 MIN', max_length=30),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('RECIBIDO', 'Recibido'), ('PREPARANDO', 'Preparando'), ('EN_CAMINO', 'En camino'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='RECIBIDO', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='repartidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='orders.repartidor'),
        ),
    ]
