# Generated by Django 5.2.17 on 2026-09-17 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_repartidor_pedido_latitud_destino_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_slug', models.SlugField(help_text='Ej: barcelona-centro, lecheria-plaza', unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.TextField()),
                ('tiempo_estimado', models.CharField(default='10-15 MIN', max_length=30)),
                ('distancia', models.CharField(default='1.2 km', max_length=30)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'sede',
                'verbose_name_plural': 'sedes',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='descuento_porcentaje',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_anterior_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='orders.sede'),
        ),
        migrations.AddField(
            model_name='producto',
            name='sedes',
            field=models.ManyToManyField(blank=True, related_name='productos', to='orders.sede'),
        ),
    ]
