# Generated by Django 5.2.17 on 2026-09-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_sede_producto_descuento_porcentaje_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprobantepago',
            name='captura_url',
        ),
        migrations.RemoveField(
            model_name='repartidor',
            name='foto_url',
        ),
        migrations.AddField(
            model_name='comprobantepago',
            name='captura',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes/', verbose_name='Captura del pago'),
        ),
        migrations.AddField(
            model_name='repartidor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='repartidores/', verbose_name='Foto del repartidor'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
