# Generated by Django 5.2.17 on 2026-09-23 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_sede_producto_descuento_porcentaje_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={},
        ),
        migrations.AddField(
            model_name='sede',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='sedes/'),
        ),
        migrations.AlterField(
            model_name='maridaje',
            name='tipo',
            field=models.CharField(choices=[('chocolate', 'Chocolate / Dulces'), ('humo', 'Humo'), ('frituras', 'Frituras / Pasapalos'), ('frutos_secos', 'Frutos Secos')], default='frituras', max_length=30),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
