# Generated by Django 5.2.17 on 2026-09-24 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_producto_options_sede_imagen_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='comprobantepago',
                    name='captura_url',
                ),
            ],
        ),
    ]
